export default [
  { name: 'Attard', slug: 'attard' },
  { name: 'Balzan', slug: 'balzan' },
  { name: 'Birgu (Vittoriosa)', slug: 'birgu' },
  { name: 'Birkirkara', slug: 'birkirkara' },
  { name: 'Birżebbuġa', slug: 'birzebbuga' },
  { name: 'Cospicua (Bormla)', slug: 'cospicua' },
  { name: 'Dingli', slug: 'dingli' },
  { name: 'Fgura', slug: 'fgura' },
  { name: 'Floriana', slug: 'floriana' },
  { name: 'Fontana', slug: 'fontana' },
  { name: 'Għajnsielem', slug: 'ghajnsielem' },
  { name: 'Għarb', slug: 'gharb' },
  { name: 'Għargħur', slug: 'gharghur' },
  { name: 'Għasri', slug: 'ghasri' },
  { name: 'Għaxaq', slug: 'ghaxaq' },
  { name: 'Gudja', slug: 'gudja' },
  { name: 'Gżira', slug: 'gzira' },
  { name: 'Ħamrun', slug: 'hamrun' },
  { name: 'Iklin', slug: 'iklin' },
  { name: 'Senglea (Isla)', slug: 'senglea-isla' },
  { name: 'Kalkara', slug: 'kalkara' },
  { name: 'Kerċem', slug: 'kercem' },
  { name: 'Kirkop', slug: 'kirkop' },
  { name: 'Lija', slug: 'lija' },
  { name: 'Luqa', slug: 'luqa' },
  { name: 'Marsa', slug: 'marsa' },
  { name: 'Marsaskala (Wied il-Għajn)', slug: 'marsaskala' },
  { name: 'Marsaxlokk', slug: 'marsaxlokk' },
  { name: 'Mdina', slug: 'mdina' },
  { name: 'Mellieħa', slug: 'mellieha' },
  { name: 'Mġarr', slug: 'mgarr' },
  { name: 'Mosta', slug: 'mosta' },
  { name: 'Mqabba', slug: 'mqabba' },
  { name: 'Msida', slug: 'msida' },
  { name: 'Mtarfa', slug: 'mtarfa' },
  { name: 'Munxar', slug: 'munxar' },
  { name: 'Nadur', slug: 'nadur' },
  { name: 'Naxxar', slug: 'naxxar' },
  { name: 'Paola (Raħal Ġdid)', slug: 'paola' },
  { name: 'Pembroke', slug: 'pembroke' },
  { name: 'Pietà', slug: 'pieta' },
  { name: 'Qala', slug: 'qala' },
  { name: 'Qormi', slug: 'qormi' },
  { name: 'Qrendi', slug: 'qrendi' },
  { name: 'Rabat (Victoria), Gozo', slug: 'rabat-gozo' },
  { name: 'Rabat, Malta', slug: 'rabat-malta' },
  { name: 'Safi', slug: 'safi' },
  { name: "St. Julian's (San Ġiljan)", slug: 'st-julians' },
  { name: "St. Paul's Bay (San Pawl il-Baħar)", slug: 'st-pauls-bay' },
  { name: 'San Ġwann', slug: 'san-gwann' },
  { name: 'San Lawrenz', slug: 'san-lawrenz' },
  { name: 'Sannat', slug: 'sannat' },
  { name: 'Santa Luċija', slug: 'santa-lucija' },
  { name: 'Santa Venera', slug: 'santa-venera' },
  { name: 'Siġġiewi', slug: 'siggiewi' },
  { name: 'Sliema', slug: 'sliema' },
  { name: 'Swieqi', slug: 'swieqi' },
  { name: 'Tarxien', slug: 'tarxien' },
  { name: 'Valletta', slug: 'valletta' },
  { name: 'Xagħra', slug: 'xaghra' },
  { name: 'Xewkija', slug: 'xewkija' },
  { name: 'Xgħajra', slug: 'xghajra' },
  { name: 'Żabbar', slug: 'zabbar' },
  { name: 'Żebbuġ, Gozo', slug: 'zebbug-gozo' },
  { name: 'Żebbuġ, Malta', slug: 'zebbug-malta' },
  { name: 'Żejtun', slug: 'zejtun' },
  { name: 'Żurrieq', slug: 'zurrieq' },
]

export const popularLocalities = [
  { name: 'Birkirkara', slug: 'birkirkara' },
  { name: 'Mosta', slug: 'mosta' },
  { name: "St. Paul's Bay (San Pawl il-Baħar)", slug: 'st-pauls-bay' },
  { name: "St. Julian's (San Ġiljan)", slug: 'st-julians' },
  { name: 'Sliema', slug: 'sliema' },
  { name: 'Naxxar', slug: 'naxxar' },
  { name: 'Qormi', slug: 'qormi' },
  { name: 'Żabbar', slug: 'zabbar' },
] as const
